(function(){
'use strict';
const $=s=>document.querySelector(s),list=$('#pairList'),template=$('#pairTemplate');let pairs=[];let dragIndex=null;
function newPair(left='',right=''){return {id:MatchingCore.uid(),left:{text:left,image:''},right:{text:right,image:''}};}
function initialise(){pairs=[newPair('Smeagol','Gollum'),newPair('Frodo','Mr. Underhill'),newPair('Gandalf','Mithrandir')];renderPairs();preview();bind();}
function bind(){['#activityTitle','#instructions','#allowRetry','#allowSolution'].forEach(s=>$(s).addEventListener('input',preview));document.querySelectorAll('input[name=feedbackMode]').forEach(x=>x.addEventListener('change',preview));$('#addPair').onclick=()=>{pairs.push(newPair());renderPairs();};$('#previewButton').onclick=preview;$('#saveDraft').onclick=()=>{MatchingStorage.save(collect());alert('Draft saved in this browser.');};$('#loadDraft').onclick=()=>{const a=MatchingStorage.load();if(!a){alert('No saved draft was found.');return;}apply(a);};$('#downloadJson').onclick=()=>MatchingExport.downloadJson(collect());$('#downloadHtml').onclick=()=>MatchingExport.downloadHtml(collect());$('#makeLink').onclick=makeLink;}
function renderPairs(){list.innerHTML='';pairs.forEach((pair,index)=>{const node=template.content.firstElementChild.cloneNode(true);node.dataset.index=index;node.querySelector('.pair-number').textContent=`Pair ${index+1}`;setSide(node,'left',pair.left);setSide(node,'right',pair.right);node.querySelector('.left-text').oninput=e=>{pair.left.text=e.target.value;preview();};node.querySelector('.right-text').oninput=e=>{pair.right.text=e.target.value;preview();};node.querySelector('.left-image').onchange=e=>readImage(e.target.files[0],data=>{pair.left.image=data;renderPairs();preview();});node.querySelector('.right-image').onchange=e=>readImage(e.target.files[0],data=>{pair.right.image=data;renderPairs();preview();});node.querySelector('.remove-left-image').onclick=()=>{pair.left.image='';renderPairs();preview();};node.querySelector('.remove-right-image').onclick=()=>{pair.right.image='';renderPairs();preview();};node.querySelector('.delete-pair').onclick=()=>{if(pairs.length<=2){alert('An activity needs at least two pairs.');return;}pairs.splice(index,1);renderPairs();preview();};node.querySelector('.move-up').onclick=()=>move(index,index-1);node.querySelector('.move-down').onclick=()=>move(index,index+1);node.addEventListener('dragstart',()=>{dragIndex=index;node.classList.add('dragging');});node.addEventListener('dragend',()=>node.classList.remove('dragging'));node.addEventListener('dragover',e=>e.preventDefault());node.addEventListener('drop',e=>{e.preventDefault();if(dragIndex!==null&&dragIndex!==index)move(dragIndex,index);dragIndex=null;});list.appendChild(node);});}
function setSide(node,side,data){node.querySelector(`.${side}-text`).value=data.text||'';const img=node.querySelector(`.${side}-preview`),remove=node.querySelector(`.remove-${side}-image`);if(data.image){img.src=data.image;img.hidden=false;remove.hidden=false;}}
function move(from,to){if(to<0||to>=pairs.length)return;const [p]=pairs.splice(from,1);pairs.splice(to,0,p);renderPairs();preview();}
function readImage(file,done){if(!file)return;if(file.size>2.5*1024*1024&&!confirm('This image is large and may make sharing links too long. Continue?'))return;const r=new FileReader();r.onload=()=>done(r.result);r.readAsDataURL(file);}
function collect(){return MatchingCore.normaliseActivity({title:$('#activityTitle').value,instructions:$('#instructions').value,feedbackMode:document.querySelector('input[name=feedbackMode]:checked').value,allowRetry:$('#allowRetry').checked,allowSolution:$('#allowSolution').checked,pairs});}
function apply(a){a=MatchingCore.normaliseActivity(a);$('#activityTitle').value=a.title;$('#instructions').value=a.instructions;document.querySelector(`input[name=feedbackMode][value=${a.feedbackMode}]`).checked=true;$('#allowRetry').checked=a.allowRetry;$('#allowSolution').checked=a.allowSolution;pairs=a.pairs;renderPairs();preview();}
function preview(){const a=collect(),root=$('#previewRoot');if(a.pairs.length<2){root.innerHTML='<p>Add at least two complete pairs to preview the activity.</p>';return;}new MatchingPlayer(root,a);}
function makeLink(){const a=collect();if(a.pairs.length<2){alert('Add at least two complete pairs.');return;}const url=MatchingExport.shareUrl(a);$('#shareLink').value=url;$('#embedCode').value=`<iframe src="${url}" title="${a.title.replace(/"/g,'&quot;')}" width="100%" height="720" style="border:0" allowfullscreen></iframe>`;const qr=$('#qrImage'),notice=$('#shareNotice');if(url.length>7000){qr.hidden=true;notice.textContent='This activity is too large for a reliable shareable URL, usually because it contains images. Download the standalone HTML file and upload it to GitHub Pages, then create a QR code from that hosted address.';}else{qr.src='https://api.qrserver.com/v1/create-qr-code/?size=420x420&data='+encodeURIComponent(url);qr.hidden=false;notice.textContent='The QR image requires an internet connection. Text-only activities work best as shareable links.';}}
document.addEventListener('DOMContentLoaded',initialise);
})();
