(function(global){
'use strict';
const DEFAULT={title:'Match the pairs',instructions:'Drag or tap to match each item with its partner.',feedbackMode:'check',allowRetry:true,allowSolution:true,pairs:[{id:'1',left:{text:'Smeagol'},right:{text:'Gollum'}},{id:'2',left:{text:'Frodo'},right:{text:'Mr. Underhill'}},{id:'3',left:{text:'Peregrin Took'},right:{text:'Pippin'}},{id:'4',left:{text:'Sauron'},right:{text:'The Lord of the Rings'}},{id:'5',left:{text:'Gandalf'},right:{text:'Mithrandir'}},{id:'6',left:{text:'Aragorn'},right:{text:'Elessar'}}]};
function decodeHash(){try{const match=location.hash.match(/activity=([^&]+)/);if(!match)return null;const binary=atob(decodeURIComponent(match[1]));const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes));}catch(e){return null;}}
function itemMarkup(item){const img=item.image?`<img src="${escapeAttr(item.image)}" alt="">`:'';const text=item.text?`<span class="item-text">${escapeHtml(item.text)}</span>`:'';return img+text;}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function escapeAttr(value){return escapeHtml(value);}
class MatchingPlayer{
 constructor(root,activity){this.root=root;this.activity=MatchingCore.normaliseActivity(activity);this.engine=new MatchingCore.MatchingEngine(this.activity);this.selected=null;this.dragged=null;this.render();}
 render(){
  this.root.innerHTML=`<header class="activity-header"><h2>${escapeHtml(this.activity.title)}</h2><p class="activity-instructions">${escapeHtml(this.activity.instructions)}</p></header><div class="match-board"><div class="match-column left-column" aria-label="Left items"></div><div class="match-column right-column" aria-label="Right items"></div></div><p class="status-message" role="status"></p><div class="activity-actions"><button class="button check-button" type="button">Check</button><button class="button button-secondary solution-button" type="button" ${this.activity.allowSolution?'':'hidden'}>Show solution</button><button class="button button-secondary retry-button" type="button" hidden>Retry</button></div>`;
  this.drawItems();this.bindActions();
 }
 drawItems(){
  const left=this.root.querySelector('.left-column'),right=this.root.querySelector('.right-column');
  left.innerHTML=this.engine.left.map(x=>this.itemButton('left',x)).join('');right.innerHTML=this.engine.right.map(x=>this.itemButton('right',x)).join('');
  this.bindItems();this.updateUsed();
 }
 itemButton(side,x){return `<button class="match-item" type="button" draggable="true" data-side="${side}" data-pair-id="${escapeAttr(x.pairId)}" aria-pressed="false">${itemMarkup(x.item)}</button>`;}
 bindItems(){this.root.querySelectorAll('.match-item').forEach(el=>{el.addEventListener('click',()=>this.select(el));el.addEventListener('dragstart',e=>{this.dragged=el;el.classList.add('dragging');e.dataTransfer.setData('text/plain',el.dataset.pairId);});el.addEventListener('dragend',()=>{el.classList.remove('dragging');this.dragged=null;});el.addEventListener('dragover',e=>{if(this.dragged&&this.dragged.dataset.side!==el.dataset.side){e.preventDefault();el.classList.add('drag-over');}});el.addEventListener('dragleave',()=>el.classList.remove('drag-over'));el.addEventListener('drop',e=>{e.preventDefault();el.classList.remove('drag-over');if(this.dragged&&this.dragged.dataset.side!==el.dataset.side)this.makeMatch(this.dragged,el);});});}
 select(el){if(el.classList.contains('used'))return;if(!this.selected){this.selected=el;el.classList.add('selected');el.setAttribute('aria-pressed','true');return;}if(this.selected===el){this.clearSelection();return;}if(this.selected.dataset.side===el.dataset.side){this.clearSelection();this.selected=el;el.classList.add('selected');el.setAttribute('aria-pressed','true');return;}this.makeMatch(this.selected,el);}
 clearSelection(){if(this.selected){this.selected.classList.remove('selected');this.selected.setAttribute('aria-pressed','false');}this.selected=null;}
 makeMatch(a,b){const left=a.dataset.side==='left'?a:b,right=a.dataset.side==='right'?a:b;const result=this.engine.match(left.dataset.pairId,right.dataset.pairId);this.clearSelection();if(!result)return;const status=this.root.querySelector('.status-message');if(this.activity.feedbackMode==='instant'&&!result.correct){left.classList.add('flash-wrong');right.classList.add('flash-wrong');status.textContent='Not quite. Try again.';setTimeout(()=>{left.classList.remove('flash-wrong');right.classList.remove('flash-wrong');status.textContent='';},750);}else{if(this.activity.feedbackMode==='instant'){left.classList.add('flash-correct');right.classList.add('flash-correct');status.textContent='Correct.';}this.updateUsed();}if(this.engine.isComplete()){if(this.activity.feedbackMode==='instant')setTimeout(()=>this.showResults(this.engine.check()),500);else status.textContent='All pairs are matched. Select Check.';}}
 updateUsed(){const ids=new Set();this.engine.matches.forEach(m=>{ids.add('left:'+m.leftPairId);ids.add('right:'+m.rightPairId);});this.root.querySelectorAll('.match-item').forEach(el=>el.classList.toggle('used',ids.has(el.dataset.side+':'+el.dataset.pairId)));}
 bindActions(){this.root.querySelector('.check-button').addEventListener('click',()=>{if(!this.engine.isComplete()){this.root.querySelector('.status-message').textContent='Match all items before checking.';return;}this.showResults(this.engine.check());});this.root.querySelector('.solution-button').addEventListener('click',()=>this.showResults(this.engine.solution(),true));this.root.querySelector('.retry-button').addEventListener('click',()=>{this.engine.reset();this.selected=null;this.render();});}
 showResults(results,solution=false){const rows=results.map(m=>{const l=this.engine.item('left',m.leftPairId)||this.activity.pairs.find(p=>p.id===m.leftPairId)?.left;const r=this.engine.item('right',m.rightPairId)||this.activity.pairs.find(p=>p.id===m.rightPairId)?.right;return `<div class="result-row ${m.correct?'correct':'incorrect'}"><div class="result-content">${itemMarkup(l)}</div><div class="result-mark" aria-label="${m.correct?'Correct':'Incorrect'}">${m.correct?'✓':'×'}</div><div class="result-content">${itemMarkup(r)}</div></div>`;}).join('');const score=solution?this.activity.pairs.length:this.engine.score();const max=this.activity.pairs.length;this.root.querySelector('.match-board').outerHTML=`<div class="results-list">${rows}</div><div class="score-wrap"><div class="score-track"><div class="score-fill" style="width:${max?score/max*100:0}%"></div></div><div class="score-text">${score}/${max}</div></div>`;this.root.querySelector('.status-message').textContent=solution?'Solution shown.':`${score} out of ${max} correct.`;this.root.querySelector('.check-button').hidden=true;this.root.querySelector('.solution-button').hidden=true;this.root.querySelector('.retry-button').hidden=!this.activity.allowRetry;}
}
function initPage(){const root=document.getElementById('activityRoot');if(!root)return;let activity=decodeHash()||DEFAULT;document.getElementById('pageTitle').textContent=activity.title||'Matching Activity';new MatchingPlayer(root,activity);}
global.MatchingPlayer=MatchingPlayer;global.MATCHING_DEFAULT=DEFAULT;document.addEventListener('DOMContentLoaded',initPage);
})(window);
